#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from PIL import Image, ImageChops


DEFAULT_MODEL = "gpt-image-1.5"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run or dry-run the torso-first pet layer generation workflow from a prepared manifest."
    )
    parser.add_argument("manifest", type=Path, help="Manifest generated by prepare_pet_generation.py")
    parser.add_argument(
        "--image-cli",
        type=Path,
        default=None,
        help="Optional path to image_gen.py. Defaults to CODEX_HOME/skills/.system/imagegen/scripts/image_gen.py",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"Image model to use. Default: {DEFAULT_MODEL}",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the image generation commands without calling the API.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing output images.",
    )
    return parser.parse_args()


def resolve_path(base_dir: Path, value: str | None) -> Path | None:
    if value is None:
        return None
    return (base_dir / value).resolve()


def find_image_cli(explicit: Path | None) -> Path:
    if explicit is not None:
        return explicit.expanduser().resolve()

    if os.getenv("IMAGE_GEN"):
        return Path(os.environ["IMAGE_GEN"]).expanduser().resolve()

    codex_home = os.getenv("CODEX_HOME")
    if codex_home:
        candidate = Path(codex_home) / "skills" / ".system" / "imagegen" / "scripts" / "image_gen.py"
        return candidate.resolve()

    return (Path.home() / ".codex" / "skills" / ".system" / "imagegen" / "scripts" / "image_gen.py").resolve()


def ensure_api_key(dry_run: bool) -> None:
    if dry_run:
        return
    if os.getenv("OPENAI_API_KEY"):
        return
    raise RuntimeError("OPENAI_API_KEY is required for a live run.")


def create_adjacency_from_parent(
    parent_image: Path,
    box: list[int],
    destination: Path,
    canvas_size: tuple[int, int],
) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    parent = Image.open(parent_image).convert("RGBA")
    crop = tuple(box)
    adjacency = Image.new("RGBA", canvas_size, (0, 0, 0, 0))
    adjacency.alpha_composite(parent.crop(crop), dest=(crop[0], crop[1]))
    adjacency.save(destination)
    return destination


def build_command(
    *,
    image_cli: Path,
    model: str,
    blank_canvas: Path,
    reference_image: Path,
    prompt_path: Path,
    mask_path: Path,
    output_path: Path,
    adjacency_image: Path | None,
    force: bool,
) -> list[str]:
    command = [
        sys.executable,
        str(image_cli),
        "edit",
        "--model",
        model,
        "--image",
        str(blank_canvas),
        "--image",
        str(reference_image),
        "--mask",
        str(mask_path),
        "--prompt-file",
        str(prompt_path),
        "--background",
        "transparent",
        "--output-format",
        "png",
        "--input-fidelity",
        "high",
        "--size",
        "1024x1024",
        "--out",
        str(output_path),
    ]
    if adjacency_image is not None:
        command.extend(["--image", str(adjacency_image)])
    if force:
        command.append("--force")
    return command


def print_command(command: list[str]) -> None:
    print(" ".join(f'"{part}"' if " " in part else part for part in command))


def validate_outputs(
    base_dir: Path,
    manifest: dict[str, Any],
) -> None:
    canvas_size = tuple(manifest["canvas_size"])
    composite = Image.new("RGBA", canvas_size, (0, 0, 0, 0))
    outputs: dict[str, Path] = {}

    for component in manifest["components"]:
        path = resolve_path(base_dir, component["output"])
        if path is None or not path.exists():
            raise RuntimeError(f"Missing output for validation: {component['name']}")
        outputs[component["name"]] = path

    for name in manifest["stack_order"]:
        composite.alpha_composite(Image.open(outputs[name]).convert("RGBA"))

    validation_path = base_dir / "validation_composite.png"
    composite.save(validation_path)

    alpha_union = Image.new("L", canvas_size, 0)
    for component in manifest["components"]:
        alpha = Image.open(outputs[component["name"]]).convert("RGBA").getchannel("A")
        alpha_union = ImageChops.lighter(alpha_union, alpha)

    subject_bbox = alpha_union.getbbox()
    report = {
        "validation_composite": str(validation_path.relative_to(base_dir)).replace("\\", "/"),
        "alpha_union_bbox": list(subject_bbox) if subject_bbox else None,
    }
    report_path = base_dir / "validation_report.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")


def main() -> None:
    args = parse_args()
    ensure_api_key(args.dry_run)

    manifest_path = args.manifest.expanduser().resolve()
    base_dir = manifest_path.parent
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    image_cli = find_image_cli(args.image_cli)
    if not image_cli.exists():
        raise RuntimeError(f"image_gen.py not found: {image_cli}")

    blank_canvas = resolve_path(base_dir, manifest["blank_canvas"])
    reference_image = resolve_path(base_dir, manifest["reference_image"])
    temp_dir = resolve_path(base_dir, manifest["temp_dir"])
    if blank_canvas is None or reference_image is None or temp_dir is None:
        raise RuntimeError("Manifest is missing required paths.")

    temp_dir.mkdir(parents=True, exist_ok=True)
    generated_outputs: dict[str, Path] = {}

    for component in manifest["components"]:
        name = component["name"]
        prompt_path = resolve_path(base_dir, component["prompt"])
        mask_path = resolve_path(base_dir, component["mask"])
        output_path = resolve_path(base_dir, component["output"])
        if prompt_path is None or mask_path is None or output_path is None:
            raise RuntimeError(f"Manifest entry is incomplete for component: {name}")

        adjacency_image = None
        if component["parent"] is not None:
            parent_name = component["parent"]
            if args.dry_run:
                adjacency_image = resolve_path(base_dir, component["adjacency_preview"])
            else:
                parent_output = generated_outputs[parent_name]
                adjacency_image = create_adjacency_from_parent(
                    parent_output,
                    component["adjacency_box"],
                    temp_dir / f"{name}_adjacency.png",
                    tuple(manifest["canvas_size"]),
                )

        command = build_command(
            image_cli=image_cli,
            model=args.model,
            blank_canvas=blank_canvas,
            reference_image=reference_image,
            prompt_path=prompt_path,
            mask_path=mask_path,
            output_path=output_path,
            adjacency_image=adjacency_image,
            force=args.force,
        )

        print(f"[{name}]")
        print_command(command)

        if args.dry_run:
            continue

        subprocess.run(command, check=True)
        generated_outputs[name] = output_path

    if not args.dry_run:
        validate_outputs(base_dir, manifest)


if __name__ == "__main__":
    main()
